//%attributes = {"invisible":true}
C_OBJECT:C1216(MOBILE APP Get sessions info ;$0)
C_OBJECT:C1216(MOBILE APP Get session info ;$0)
C_TEXT:C284(MOBILE APP Get session info ;$1)
C_TEXT:C284(MOBILE APP Get session info ;$2)


C_TEXT:C284(MOBILE APP SESSION MANAGEMENT ;$1)

C_OBJECT:C1216(MOBILE APP SESSION UPDATE ;$1)
C_TEXT:C284(MOBILE APP SESSION UPDATE ;$2)